## Numpy Operations

Standard operators are overloaded for vector/vector and vector/scalar operations. These are implemented as vectorized operations that bypasses Python's high overhead and exploits processing efficiencies. Here we'll look at just a few of those supplied by NumPy.

In [0]:
import numpy as np

In [0]:
a = np.arange(1, 4)
b = np.arange(4, 7)
print('a: ', a)
print('b: ', b)

a:  [1 2 3]
b:  [4 5 6]


In [0]:
# scalar addition and multiplication
print(a + 2)
print(a * 2)
print('a is unchanged: ', a)

[3 4 5]
[2 4 6]
a is unchanged:  [1 2 3]


In [0]:
# pairwise vector addition and multiplication
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


There are a range of element-wise operations.

In [0]:
x = np.random.randint(0, 10, 8)
print('x: ', x)

x:  [8 5 5 1 2 0 8 9]


In [0]:
print(x.min())
print(x.max())
print(np.sqrt(x))

0
9
[2.82842712 2.23606798 2.23606798 1.         1.41421356 0.
 2.82842712 3.        ]


Finding the indexes of minimum and maximum values.

In [0]:
print(x)
print(x.argmin())
print(x.argmax())

[8 5 5 1 2 0 8 9]
5
7


In [0]:
# create a boolean array satisfying the condition
print(np.greater(x, 4))

[ True  True  True False False False  True  True]


## Sorting

NumPy arrays are sorted in place. In the case of multidimensional arrays, sorting defaults to the outermost axis. You can use the *axis* keyword argument to specify the dimension to sort across.

In [0]:
x = np.random.randint(0, 10, 8)
print(x)
x.sort()
print(x)

[7 8 2 0 4 5 2 0]
[0 0 2 2 4 5 7 8]


In [0]:
xy = np.random.randint(0, 10, (2,8))
print(xy)

[[1 2 5 9 3 6 2 2]
 [4 0 8 9 5 5 9 0]]


In [0]:
xy.sort()  # sort along each row: default axis=-1
print(xy)

[[1 2 2 2 3 5 6 9]
 [0 0 4 5 5 8 9 9]]


In [0]:
xy.sort(axis=0)  # sort down each column
print(xy)

[[0 0 2 2 3 5 6 9]
 [1 2 4 5 5 8 9 9]]


The *argsort* function returns the indexes that would sort the array.

In [0]:
x = np.random.randint(0, 10, 8)
indx_x = x.argsort()
print(x)
print(indx_x)
# sanity check:
for i in indx_x:
    print(x[i], end=' ')

[1 7 2 5 2 1 7 3]
[0 5 2 4 7 3 1 6]
1 1 2 2 3 5 7 7 

## Reduction

In [0]:
x = np.random.randint(0, 10, 8)
y = np.random.randint(0, 10, 8)
print('x: ', x)
print('y: ', y)
print(np.maximum(x, y))
print(np.minimum(x, y))

x:  [7 3 0 2 4 1 7 2]
y:  [4 9 8 7 0 2 0 3]
[7 9 8 7 4 2 7 3]
[4 3 0 2 0 1 0 2]


In [0]:
c = np.arange(1, 6)
print(c)
print(np.add.reduce(c))
print(np.multiply.reduce(c))

[1 2 3 4 5]
15
120


We can also accumulate results into a new array as we go.

In [0]:
print(c)
print(np.add.accumulate(c))
print(np.multiply.accumulate(c))

[1 2 3 4 5]
[ 1  3  6 10 15]
[  1   2   6  24 120]


Operations can also be applied to multidimensional arrays.

In [0]:
e = np.random.randint(0, 10, (3,4))
print(e)

[[6 4 4 8]
 [1 1 0 2]
 [6 0 6 0]]


In [0]:
# over all elements
print(e.sum())
print(e.max())
print(e.min())
print(e.mean())

38
8
0
3.1666666666666665


In [0]:
# down the columns
print(e, '\n')
print(e.sum(axis=0))
print(e.max(axis=0))
print(e.min(axis=0))
print(e.mean(axis=0))

[[6 4 4 8]
 [1 1 0 2]
 [6 0 6 0]] 

[13  5 10 10]
[6 4 6 8]
[1 0 0 0]
[4.33333333 1.66666667 3.33333333 3.33333333]


In [0]:
# along the rows (or outermost dimension, same as axis=-1)
print(e, '\n')
print(e.sum(axis=1))
print(e.max(axis=1))
print(e.min(axis=1))
print(e.mean(axis=1))

[[6 4 4 8]
 [1 1 0 2]
 [6 0 6 0]] 

[22  4 12]
[8 2 6]
[4 0 0]
[5.5 1.  3. ]


## Broadcasting

Broadcasting is a set of rules for applying binary operations to arrays of different shapes.

In [0]:
# broadcasting not needed when the arrays are the same size
a = np.array([0, 1, 2])
b = np.array([4, 4, 4])
print(a+b)
print(a.shape, a.shape)

[4 5 6]
(3,) (3,)


When we perform a scalar/vector operation, think of the scalar value being duplicated to an array whose shape is the same as the vector's.

In [0]:
# 4 gets 'stretched' into the array [4, 4, 4] to match the size of a
print(a, '\n')
print(a + 4)

[0 1 2] 

[4 5 6]


If we add array *a* and a 3&times;3 matrix of 1s, a is replicated into a stack of *a*s to match the shape of the matrix.

In [0]:
print(a, '\n')
ones = np.ones((3, 3))
print(a.shape, ones.shape, '\n')
print(ones, '\n')
print(ones + a)

[0 1 2] 

(3,) (3, 3) 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


If neither operand can be expanded to match the size of the other, broadcasting allows for *both* arrays to be expanded into a common shape.

In [0]:
a = np.arange(3)
b = np.reshape(a, (3,1))
print(a.shape, b.shape, '\n')
print(a, '\n')
print(b, '\n')
print(a + b)

(3,) (3, 1) 

[0 1 2] 

[[0]
 [1]
 [2]] 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


We briefly relate the rules of broadcasting. To do so, we'll apply the rules to an array *g* allowing us to add it to an array *f* of different shape. 

*Rule 1:* If the two arrays differ in their number of dimensions, the **shape** of the one with fewer dimensions is padded with ones on its leading (left) side.

In [0]:
f = np.ones((2, 3))
g = np.arange(3)
print(f, '\n')
print(g, '\n')
print(f.shape, g.shape)

[[1. 1. 1.]
 [1. 1. 1.]] 

[0 1 2] 

(2, 3) (3,)


In [0]:
gp = g.reshape((1, 3))
print(gp, '\n')
print(f.shape, gp.shape)

[[0 1 2]] 

(2, 3) (1, 3)


*Rule 2:* If the shape of the two arrays does not match in any dimension, the array with **shape** equal to 1 in that dimension is stretched to match the other shape.

In [0]:
gpp = np.repeat(gp, 2, axis=0)
print(gpp, '\n')
print(f, '\n')
print(f.shape, gpp.shape)

[[0 1 2]
 [0 1 2]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

(2, 3) (2, 3)


Now the arrays have the same shape and the operation can be applied.

In [0]:
# these yield the same result
print(f + gpp, '\n')
print(f.shape, g.shape, '\n')
print(f + g, '\n')

[[1. 2. 3.]
 [1. 2. 3.]] 

(2, 3) (3,) 

[[1. 2. 3.]
 [1. 2. 3.]] 



*Rule 3:* If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [0]:
gppp = np.repeat(gp, 3, axis=0)
print(f, '\n')
print(gppp, '\n')
print(f.shape, gppp.shape)

[[1. 1. 1.]
 [1. 1. 1.]] 

[[0 1 2]
 [0 1 2]
 [0 1 2]] 

(2, 3) (3, 3)


In [0]:
# these two arrays cannot be operated on since broadcasting will not work
f + gppp  # an error

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 